### ISSUE TITLE
Cambiar el título del repo por HourOfCode2015

### ISSUE THREAD

**Issue by renatolrr** [Open-XXI/HourOfCode2015#2]
Pues eso, que no es el CodeHour.

**Comment by renatolrr** [comment]
Lo cambio?

**Comment by Makova** [comment]
Cambia desde local y subes los cambios. Yo le hago liego un pull para  tener el cambio en mi repo local.

**Comment by renatolrr** [comment]
Ya lo he cambiado y cierro.
Se llama HourOfCode2015

**Comment by renatolrr** [comment]
Se cierra.
